apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-file-server.fullname" . }}
  labels:
    {{- include "static-file-server.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-file-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "static-file-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: webroot
              mountPath: {{ default "/web" .Values.config.folder }}
              readOnly: true
            {{- with .Values.deployment.additionalVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- if hasKey .Values.config "cors" }}
            - name: CORS
              value: {{ .Values.config.cors | quote }}
            {{- end }}
            {{- if hasKey .Values.config "debug" }}
            - name: DEBUG
              value: {{ .Values.config.debug | quote }}
            {{- end }}
            {{- if hasKey .Values.config "host" }}
            - name: HOST
              value: {{ .Values.config.host | quote }}
            {{- end }}
            {{- if hasKey .Values.config "port" }}
            - name: PORT
              value: {{ .Values.config.port | quote }}
            {{- end }}
            {{- if hasKey .Values.config "showListing" }}
            - name: SHOW_LISTING
              value: {{ .Values.config.showListing | quote }}
            {{- end }}
            {{- if hasKey .Values.config "folder" }}
            - name: FOLDER
              value: {{ .Values.config.folder | quote }}
            {{- end }}
            {{- if hasKey .Values.config "urlPrefix" }}
            - name: URL_PREFIX
              value: {{ .Values.config.urlPrefix | quote }}
            {{- end }}
            {{- if hasKey .Values.config "tlsCert" }}
            - name: TLS_CERT
              value: {{ .Values.config.tlsCert | quote }}
            {{- end }}
            {{- if hasKey .Values.config "tlsKey" }}
            - name: TLS_KEY
              value: {{ .Values.config.tlsKey | quote }}
            {{- end }}
            {{- if hasKey .Values.config "tlsMinVers" }}
            - name: TLS_MIN_VERS
              value: {{ .Values.config.tlsMinVers | quote }}
            {{- end }}
            {{- if hasKey .Values.config "referrers" }}
            - name: REFERRERS
              value: {{ .Values.config.referrers | quote }}
            {{- end }}
            {{- with .Values.deployment.additionalEnvVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          args:
            {{- with .Values.deployment.additionalArguments }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ default 8080 .Values.config.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.deployment.additionalContainers }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
