apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-file-server.fullname" . }}
  labels:
    {{- include "static-file-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default 8080 .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "static-file-server.selectorLabels" . | nindent 4 }}
