{{- if .Values.traefik.ingressRoute.enabled -}}
{{- $fullName := include "aria2.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-rpc
  labels:
    {{- include "aria2.labels" . | nindent 4 }}
  {{- with .Values.traefik.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.traefik.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: {{ .Values.traefik.ingressRoute.matchRule }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.port }}
          {{- if .Values.traefik.ingressRoute.serversTransport }}
          serversTransport: {{ .Values.traefik.ingressRoute.serversTransport }}
          {{- end }}
      {{- if .Values.traefik.ingressRoute.middlewares }}
      middlewares:
        {{- toYaml .Values.traefik.ingressRoute.middlewares | nindent 8 }}
      {{- end }}
  {{- if .Values.traefik.ingressRoute.tls }}
  tls:
    {{- toYaml .Values.traefik.ingressRoute.tls | nindent 4 }}
  {{- end }}
{{- end }}
