{{- if .Values.traefik.ingressRouteTcp.enabled -}}
{{- $fullName := include "aria2.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-tcp
  labels:
    {{- include "aria2.labels" . | nindent 4 }}
  {{- with .Values.traefik.ingressRouteTcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.traefik.ingressRouteTcp.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: {{ .Values.traefik.ingressRouteTcp.matchRule }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.btTcpPort }}
      {{- if .Values.traefik.ingressRouteTcp.middlewares }}
      middlewares:
        {{- toYaml .Values.traefik.ingressRouteTcp.middlewares | nindent 8 }}
      {{- end }}
  {{- if .Values.traefik.ingressRouteTcp.tls }}
  tls:
    {{- toYaml .Values.traefik.ingressRouteTcp.tls | nindent 4 }}
  {{- end }}
{{- end }}
