{{- $defaultMetadata := fromYaml (include "generic.defaultMetadata" .) -}}
{{- $defaultDeploymentSpec := fromYaml (include "generic.defaultDeploymentSpec" .) -}}
{{- range .Values.resources }}
---
{{- if .enabled }}
apiVersion: {{ .apiVersion }}
kind: {{ .kind }}
metadata:
  name: {{ include "generic.fullname" $ }}{{ if .name }}-{{ .name }}{{ end }}
  {{- toYaml (merge (default .metadata) $defaultMetadata) | nindent 2 }}
spec:
  {{- if or (eq .kind "Deployment") (eq .kind "DaemonSet") }}
  {{- toYaml (merge (default .spec) $defaultDeploymentSpec) | nindent 2 }}
  {{- else }}
  {{- toYaml (default .spec) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
