{{- range .Values.resources }}
---
{{- if .enabled }}
{{- $defaultSpec := default dict -}}
{{- if or (eq .kind "Deployment") (eq .kind "DaemonSet") -}}
  {{- $defaultSpec = fromYaml (include "generic.defaultDeploymentSpec" $) -}}
{{- else -}}
  {{- if eq .kind "Service" -}}
    {{- $defaultSpec = fromYaml (include "generic.defaultServiceSpec" $) -}}
  {{- else -}}
    {{- if eq .kind "CiliumNetworkPolicy" -}}
      {{- $defaultSpec = fromYaml (include "generic.defaultCiliumNetworkPolicySpec" $) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
apiVersion: {{ .apiVersion }}
kind: {{ .kind }}
metadata:
  name: {{ include "generic.fullname" $ }}{{ if .name }}-{{ .name }}{{ end }}
  {{- toYaml (merge (default .metadata) (fromYaml (include "generic.defaultMetadata" $))) | nindent 2 }}
spec:
  {{- toYaml (merge (default .spec) $defaultSpec) | nindent 2 }}
{{- end }}
{{- end }}
