{{- $fullName := include "generic.fullname" . -}}
{{- range .Values.ciliumNetworkPolicies }}
---
{{- if .enabled -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ $fullName }}-{{ .name | default "default" }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "generic.selectorLabels" $ | nindent 6 }}
  {{- with .ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .ingressDeny }}
  ingressDeny:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .egressDeny }}
  egressDeny:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}