{{- $fullName := include "generic.fullname" . -}}
{{- range .Values.ingressRoutes }}
---
{{- if .enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: {{ .kind | default "IngressRoute" }}
metadata:
  name: {{ $fullName }}-{{ .name | default "default" }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    {{- range .routes }}
    - services:
        - name: {{ $fullName }}-{{ .svcName | default "default" }}
          {{- $port := .svcPort -}}
          {{- range $.Values.ports }}
          {{- if eq .name $port}}
          port: {{ .svcPort }}
          {{- end }}
          {{- end }}
      {{- if .match }}
      match: {{ .match }}
      {{- end }}
      {{- if .kind }}
      kind: {{ .kind }}
      {{- end }}
      {{- if .middlewares }}
      middlewares:
        {{- toYaml .middlewares | nindent 8 }}
      {{- end }}
      {{- if ge .priority 0 }}
      priority: {{ .priority }}
      {{- end }}
    {{- end }}
  {{- if .tls }}
  tls:
    {{- toYaml .tls | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
