{{- $fullName := include "generic.fullname" . -}}
{{- range .Values.services }}
---
{{- if .enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ .name | default "default" }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "generic.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  ports:
    {{- range .ports }}
    {{- $port := . -}}
    {{- range $.Values.ports }}
    {{- if eq .name $port }}
    - port: {{ .svcPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- with .additionalParameters }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}